sudo: false
language: node_js
cache:
  directories:
    - node_modules
script:
  - yarn
  - npm run deploy
  - ngh --no-silent --repo=https://GH_TOKEN@github.com/meeroslav/angular-seed.git --name="meeroslav" --email=missing.manual@gmail.com

notifications:
  email: false
node_js:
  - '8'
before_install:
  - export CHROME_BIN=chromium-browser
  - npm i -g npm@^3
before_script:
  - npm prune
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
