System.config({
  baseURL: ".",
  defaultJSExtensions: true,
  transpiler: false,
  paths: {
    "github:*": "jspm_packages/github/*",
    "npm:*": "jspm_packages/npm/*"
  },
  bundles: {
    "lib/bootstrap.bundle.js": [
      "npm:reflect-metadata@0.1.3.js",
      "npm:reflect-metadata@0.1.3/Reflect.js",
      "github:jspm/nodelibs-process@0.1.2.js",
      "github:jspm/nodelibs-process@0.1.2/index.js",
      "npm:process@0.11.3.js",
      "npm:process@0.11.3/browser.js",
      "github:jspm/nodelibs-crypto@0.1.0.js",
      "github:jspm/nodelibs-crypto@0.1.0/index.js",
      "npm:crypto-browserify@3.11.0.js",
      "npm:crypto-browserify@3.11.0/index.js",
      "npm:public-encrypt@4.0.0.js",
      "npm:public-encrypt@4.0.0/browser.js",
      "npm:public-encrypt@4.0.0/privateDecrypt.js",
      "github:jspm/nodelibs-buffer@0.1.0.js",
      "github:jspm/nodelibs-buffer@0.1.0/index.js",
      "npm:buffer@3.6.0.js",
      "npm:buffer@3.6.0/index.js",
      "npm:isarray@1.0.0.js",
      "npm:isarray@1.0.0/index.js",
      "npm:ieee754@1.1.6.js",
      "npm:ieee754@1.1.6/index.js",
      "npm:base64-js@0.0.8.js",
      "npm:base64-js@0.0.8/lib/b64.js",
      "npm:public-encrypt@4.0.0/withPublic.js",
      "npm:bn.js@4.11.3.js",
      "npm:bn.js@4.11.3/lib/bn.js",
      "npm:create-hash@1.1.2.js",
      "npm:create-hash@1.1.2/browser.js",
      "npm:cipher-base@1.0.2.js",
      "npm:cipher-base@1.0.2/index.js",
      "github:jspm/nodelibs-string_decoder@0.1.0.js",
      "github:jspm/nodelibs-string_decoder@0.1.0/index.js",
      "npm:string_decoder@0.10.31.js",
      "npm:string_decoder@0.10.31/index.js",
      "npm:inherits@2.0.1.js",
      "npm:inherits@2.0.1/inherits_browser.js",
      "github:jspm/nodelibs-stream@0.1.0.js",
      "github:jspm/nodelibs-stream@0.1.0/index.js",
      "npm:stream-browserify@1.0.0.js",
      "npm:stream-browserify@1.0.0/index.js",
      "npm:readable-stream@1.1.14/passthrough.js",
      "npm:readable-stream@1.1.14/lib/_stream_passthrough.js",
      "npm:core-util-is@1.0.2.js",
      "npm:core-util-is@1.0.2/lib/util.js",
      "npm:readable-stream@1.1.14/lib/_stream_transform.js",
      "npm:readable-stream@1.1.14/lib/_stream_duplex.js",
      "npm:readable-stream@1.1.14/lib/_stream_writable.js",
      "npm:readable-stream@1.1.14/lib/_stream_readable.js",
      "github:jspm/nodelibs-events@0.1.1.js",
      "github:jspm/nodelibs-events@0.1.1/index.js",
      "npm:events@1.0.2.js",
      "npm:events@1.0.2/events.js",
      "npm:isarray@0.0.1.js",
      "npm:isarray@0.0.1/index.js",
      "npm:readable-stream@1.1.14/transform.js",
      "npm:readable-stream@1.1.14/duplex.js",
      "npm:readable-stream@1.1.14/writable.js",
      "npm:readable-stream@1.1.14/readable.js",
      "npm:sha.js@2.4.5.js",
      "npm:sha.js@2.4.5/index.js",
      "npm:sha.js@2.4.5/sha512.js",
      "npm:sha.js@2.4.5/hash.js",
      "npm:sha.js@2.4.5/sha384.js",
      "npm:sha.js@2.4.5/sha256.js",
      "npm:sha.js@2.4.5/sha224.js",
      "npm:sha.js@2.4.5/sha1.js",
      "npm:sha.js@2.4.5/sha.js",
      "npm:ripemd160@1.0.1.js",
      "npm:ripemd160@1.0.1/lib/ripemd160.js",
      "npm:create-hash@1.1.2/md5.js",
      "npm:create-hash@1.1.2/helpers.js",
      "npm:browserify-rsa@4.0.1.js",
      "npm:browserify-rsa@4.0.1/index.js",
      "npm:randombytes@2.0.3.js",
      "npm:randombytes@2.0.3/browser.js",
      "npm:public-encrypt@4.0.0/xor.js",
      "npm:public-encrypt@4.0.0/mgf.js",
      "npm:parse-asn1@5.0.0.js",
      "npm:parse-asn1@5.0.0/index.js",
      "npm:pbkdf2@3.0.4.js",
      "npm:pbkdf2@3.0.4/browser.js",
      "npm:create-hmac@1.1.4.js",
      "npm:create-hmac@1.1.4/browser.js",
      "npm:browserify-aes@1.0.6.js",
      "npm:browserify-aes@1.0.6/browser.js",
      "npm:browserify-aes@1.0.6/modes.js",
      "npm:browserify-aes@1.0.6/decrypter.js",
      "npm:browserify-aes@1.0.6/modes/ctr.js",
      "npm:buffer-xor@1.0.3.js",
      "npm:buffer-xor@1.0.3/index.js",
      "npm:browserify-aes@1.0.6/modes/ofb.js",
      "npm:browserify-aes@1.0.6/modes/cfb1.js",
      "npm:browserify-aes@1.0.6/modes/cfb8.js",
      "npm:browserify-aes@1.0.6/modes/cfb.js",
      "npm:browserify-aes@1.0.6/modes/cbc.js",
      "npm:browserify-aes@1.0.6/modes/ecb.js",
      "npm:evp_bytestokey@1.0.0.js",
      "npm:evp_bytestokey@1.0.0/index.js",
      "npm:browserify-aes@1.0.6/authCipher.js",
      "npm:browserify-aes@1.0.6/ghash.js",
      "npm:browserify-aes@1.0.6/aes.js",
      "npm:browserify-aes@1.0.6/streamCipher.js",
      "npm:browserify-aes@1.0.6/encrypter.js",
      "npm:parse-asn1@5.0.0/fixProc.js",
      "npm:parse-asn1@5.0.0/aesid.json!github:systemjs/plugin-json@0.1.2.js",
      "npm:parse-asn1@5.0.0/asn1.js",
      "npm:asn1.js@4.6.0.js",
      "npm:asn1.js@4.6.0/lib/asn1.js",
      "npm:asn1.js@4.6.0/lib/asn1/encoders/index.js",
      "npm:asn1.js@4.6.0/lib/asn1/encoders/pem.js",
      "npm:asn1.js@4.6.0/lib/asn1/encoders/der.js",
      "npm:asn1.js@4.6.0/lib/asn1/decoders/index.js",
      "npm:asn1.js@4.6.0/lib/asn1/decoders/pem.js",
      "npm:asn1.js@4.6.0/lib/asn1/decoders/der.js",
      "npm:asn1.js@4.6.0/lib/asn1/constants/index.js",
      "npm:asn1.js@4.6.0/lib/asn1/constants/der.js",
      "npm:asn1.js@4.6.0/lib/asn1/base/index.js",
      "npm:asn1.js@4.6.0/lib/asn1/base/node.js",
      "npm:minimalistic-assert@1.0.0.js",
      "npm:minimalistic-assert@1.0.0/index.js",
      "npm:asn1.js@4.6.0/lib/asn1/base/buffer.js",
      "npm:asn1.js@4.6.0/lib/asn1/base/reporter.js",
      "npm:asn1.js@4.6.0/lib/asn1/api.js",
      "github:jspm/nodelibs-vm@0.1.0.js",
      "github:jspm/nodelibs-vm@0.1.0/index.js",
      "npm:vm-browserify@0.0.4.js",
      "npm:vm-browserify@0.0.4/index.js",
      "npm:indexof@0.0.1.js",
      "npm:indexof@0.0.1/index.js",
      "npm:public-encrypt@4.0.0/publicEncrypt.js",
      "npm:create-ecdh@4.0.0.js",
      "npm:create-ecdh@4.0.0/browser.js",
      "npm:elliptic@6.2.3.js",
      "npm:elliptic@6.2.3/lib/elliptic.js",
      "npm:elliptic@6.2.3/lib/elliptic/eddsa/index.js",
      "npm:elliptic@6.2.3/lib/elliptic/eddsa/signature.js",
      "npm:elliptic@6.2.3/lib/elliptic/eddsa/key.js",
      "npm:hash.js@1.0.3.js",
      "npm:hash.js@1.0.3/lib/hash.js",
      "npm:hash.js@1.0.3/lib/hash/hmac.js",
      "npm:hash.js@1.0.3/lib/hash/ripemd.js",
      "npm:hash.js@1.0.3/lib/hash/sha.js",
      "npm:hash.js@1.0.3/lib/hash/common.js",
      "npm:hash.js@1.0.3/lib/hash/utils.js",
      "npm:elliptic@6.2.3/lib/elliptic/ec/index.js",
      "npm:elliptic@6.2.3/lib/elliptic/ec/signature.js",
      "npm:elliptic@6.2.3/lib/elliptic/ec/key.js",
      "npm:elliptic@6.2.3/lib/elliptic/curves.js",
      "npm:elliptic@6.2.3/lib/elliptic/precomputed/secp256k1.js",
      "npm:elliptic@6.2.3/lib/elliptic/curve/index.js",
      "npm:elliptic@6.2.3/lib/elliptic/curve/edwards.js",
      "npm:elliptic@6.2.3/lib/elliptic/curve/mont.js",
      "npm:elliptic@6.2.3/lib/elliptic/curve/short.js",
      "npm:elliptic@6.2.3/lib/elliptic/curve/base.js",
      "npm:elliptic@6.2.3/lib/elliptic/hmac-drbg.js",
      "npm:brorand@1.0.5.js",
      "npm:brorand@1.0.5/index.js",
      "npm:elliptic@6.2.3/lib/elliptic/utils.js",
      "npm:elliptic@6.2.3/package.json!github:systemjs/plugin-json@0.1.2.js",
      "npm:browserify-sign@4.0.0.js",
      "npm:browserify-sign@4.0.0/browser.js",
      "npm:browserify-sign@4.0.0/verify.js",
      "npm:browserify-sign@4.0.0/curves.js",
      "npm:browserify-sign@4.0.0/sign.js",
      "npm:browserify-sign@4.0.0/algos.js",
      "npm:diffie-hellman@5.0.2.js",
      "npm:diffie-hellman@5.0.2/browser.js",
      "npm:diffie-hellman@5.0.2/lib/dh.js",
      "npm:diffie-hellman@5.0.2/lib/generatePrime.js",
      "npm:miller-rabin@4.0.0.js",
      "npm:miller-rabin@4.0.0/lib/mr.js",
      "npm:diffie-hellman@5.0.2/lib/primes.json!github:systemjs/plugin-json@0.1.2.js",
      "npm:browserify-cipher@1.0.0.js",
      "npm:browserify-cipher@1.0.0/browser.js",
      "npm:browserify-des@1.0.0/modes.js",
      "npm:browserify-des@1.0.0.js",
      "npm:browserify-des@1.0.0/index.js",
      "npm:des.js@1.0.0.js",
      "npm:des.js@1.0.0/lib/des.js",
      "npm:des.js@1.0.0/lib/des/ede.js",
      "npm:des.js@1.0.0/lib/des/cbc.js",
      "npm:des.js@1.0.0/lib/des/des.js",
      "npm:des.js@1.0.0/lib/des/cipher.js",
      "npm:des.js@1.0.0/lib/des/utils.js",
      "npm:ng2-translate@2.1.0/ng2-translate.js",
      "npm:ng2-translate@2.1.0/src/translate.parser.js",
      "npm:ng2-translate@2.1.0/src/translate.service.js",
      "npm:rxjs@5.0.0-beta.7/add/operator/toArray.js",
      "npm:rxjs@5.0.0-beta.7/operator/toArray.js",
      "npm:rxjs@5.0.0-beta.7/Subscriber.js",
      "npm:rxjs@5.0.0-beta.7/Observer.js",
      "npm:rxjs@5.0.0-beta.7/symbol/rxSubscriber.js",
      "npm:rxjs@5.0.0-beta.7/util/root.js",
      "npm:rxjs@5.0.0-beta.7/Subscription.js",
      "npm:rxjs@5.0.0-beta.7/util/UnsubscriptionError.js",
      "npm:rxjs@5.0.0-beta.7/util/errorObject.js",
      "npm:rxjs@5.0.0-beta.7/util/tryCatch.js",
      "npm:rxjs@5.0.0-beta.7/util/isFunction.js",
      "npm:rxjs@5.0.0-beta.7/util/isObject.js",
      "npm:rxjs@5.0.0-beta.7/util/isArray.js",
      "npm:rxjs@5.0.0-beta.7/Observable.js",
      "npm:symbol-observable@0.2.4.js",
      "npm:symbol-observable@0.2.4/index.js",
      "npm:symbol-observable@0.2.4/ponyfill.js",
      "npm:rxjs@5.0.0-beta.7/util/toSubscriber.js",
      "npm:rxjs@5.0.0-beta.7/add/operator/merge.js",
      "npm:rxjs@5.0.0-beta.7/operator/merge.js",
      "npm:rxjs@5.0.0-beta.7/util/isScheduler.js",
      "npm:rxjs@5.0.0-beta.7/operator/mergeAll.js",
      "npm:rxjs@5.0.0-beta.7/util/subscribeToResult.js",
      "npm:rxjs@5.0.0-beta.7/InnerSubscriber.js",
      "npm:rxjs@5.0.0-beta.7/symbol/iterator.js",
      "npm:rxjs@5.0.0-beta.7/util/isPromise.js",
      "npm:rxjs@5.0.0-beta.7/OuterSubscriber.js",
      "npm:rxjs@5.0.0-beta.7/observable/ArrayObservable.js",
      "npm:rxjs@5.0.0-beta.7/observable/EmptyObservable.js",
      "npm:rxjs@5.0.0-beta.7/observable/ScalarObservable.js",
      "npm:rxjs@5.0.0-beta.7/add/operator/map.js",
      "npm:rxjs@5.0.0-beta.7/operator/map.js",
      "npm:rxjs@5.0.0-beta.7/add/operator/share.js",
      "npm:rxjs@5.0.0-beta.7/operator/share.js",
      "npm:rxjs@5.0.0-beta.7/Subject.js",
      "npm:rxjs@5.0.0-beta.7/util/ObjectUnsubscribedError.js",
      "npm:rxjs@5.0.0-beta.7/util/throwError.js",
      "npm:rxjs@5.0.0-beta.7/SubjectSubscription.js",
      "npm:rxjs@5.0.0-beta.7/operator/multicast.js",
      "npm:rxjs@5.0.0-beta.7/observable/ConnectableObservable.js",
      "npm:rxjs@5.0.0-beta.7/add/observable/of.js",
      "npm:rxjs@5.0.0-beta.7/observable/of.js",
      "npm:@angular/http@2.0.0-rc.1.js",
      "npm:@angular/http@2.0.0-rc.1/index.js",
      "npm:@angular/http@2.0.0-rc.1/http.js",
      "npm:@angular/http@2.0.0-rc.1/src/url_search_params.js",
      "npm:@angular/http@2.0.0-rc.1/src/facade/collection.js",
      "npm:@angular/http@2.0.0-rc.1/src/facade/lang.js",
      "npm:@angular/http@2.0.0-rc.1/src/enums.js",
      "npm:@angular/http@2.0.0-rc.1/src/headers.js",
      "npm:@angular/http@2.0.0-rc.1/src/facade/exceptions.js",
      "npm:@angular/http@2.0.0-rc.1/src/facade/exception_handler.js",
      "npm:@angular/http@2.0.0-rc.1/src/facade/base_wrapped_exception.js",
      "npm:@angular/http@2.0.0-rc.1/src/interfaces.js",
      "npm:@angular/http@2.0.0-rc.1/src/static_response.js",
      "npm:@angular/http@2.0.0-rc.1/src/http_utils.js",
      "npm:@angular/http@2.0.0-rc.1/src/static_request.js",
      "npm:@angular/http@2.0.0-rc.1/src/base_response_options.js",
      "npm:@angular/core@2.0.0-rc.1.js",
      "npm:@angular/core@2.0.0-rc.1/index.js",
      "npm:@angular/core@2.0.0-rc.1/private_export.js",
      "npm:@angular/core@2.0.0-rc.1/src/console.js",
      "npm:@angular/core@2.0.0-rc.1/src/di/decorators.js",
      "npm:@angular/core@2.0.0-rc.1/src/util/decorators.js",
      "npm:@angular/core@2.0.0-rc.1/src/facade/lang.js",
      "npm:@angular/core@2.0.0-rc.1/src/di/metadata.js",
      "npm:@angular/core@2.0.0-rc.1/src/di/provider_util.js",
      "npm:@angular/core@2.0.0-rc.1/src/di/provider.js",
      "npm:@angular/core@2.0.0-rc.1/src/facade/exceptions.js",
      "npm:@angular/core@2.0.0-rc.1/src/facade/exception_handler.js",
      "npm:@angular/core@2.0.0-rc.1/src/facade/collection.js",
      "npm:@angular/core@2.0.0-rc.1/src/facade/base_wrapped_exception.js",
      "npm:@angular/core@2.0.0-rc.1/src/debug/debug_renderer.js",
      "npm:@angular/core@2.0.0-rc.1/src/debug/debug_node.js",
      "npm:@angular/core@2.0.0-rc.1/src/reflection/reflection_capabilities.js",
      "npm:@angular/core@2.0.0-rc.1/src/profile/wtf_init.js",
      "npm:@angular/core@2.0.0-rc.1/src/linker/template_ref.js",
      "npm:@angular/core@2.0.0-rc.1/src/render/api.js",
      "npm:@angular/core@2.0.0-rc.1/src/change_detection/change_detection_util.js",
      "npm:@angular/core@2.0.0-rc.1/src/linker/debug_context.js",
      "npm:@angular/core@2.0.0-rc.1/src/linker/view_type.js",
      "npm:@angular/core@2.0.0-rc.1/src/metadata/view.js",
      "npm:@angular/core@2.0.0-rc.1/src/linker/view_utils.js",
      "npm:@angular/core@2.0.0-rc.1/src/application_tokens.js",
      "npm:@angular/core@2.0.0-rc.1/src/di.js",
      "npm:@angular/core@2.0.0-rc.1/src/di/opaque_token.js",
      "npm:@angular/core@2.0.0-rc.1/src/di/reflective_exceptions.js",
      "npm:@angular/core@2.0.0-rc.1/src/di/reflective_key.js",
      "npm:@angular/core@2.0.0-rc.1/src/di/forward_ref.js",
      "npm:@angular/core@2.0.0-rc.1/src/di/reflective_provider.js",
      "npm:@angular/core@2.0.0-rc.1/src/reflection/reflection.js",
      "npm:@angular/core@2.0.0-rc.1/src/reflection/reflector.js",
      "npm:@angular/core@2.0.0-rc.1/src/reflection/reflector_reader.js",
      "npm:@angular/core@2.0.0-rc.1/src/di/reflective_injector.js",
      "npm:@angular/core@2.0.0-rc.1/src/di/injector.js",
      "npm:@angular/core@2.0.0-rc.1/src/change_detection/change_detection.js",
      "npm:@angular/core@2.0.0-rc.1/src/change_detection/change_detector_ref.js",
      "npm:@angular/core@2.0.0-rc.1/src/change_detection/constants.js",
      "npm:@angular/core@2.0.0-rc.1/src/change_detection/differs/default_keyvalue_differ.js",
      "npm:@angular/core@2.0.0-rc.1/src/change_detection/differs/keyvalue_differs.js",
      "npm:@angular/core@2.0.0-rc.1/src/change_detection/differs/default_iterable_differ.js",
      "npm:@angular/core@2.0.0-rc.1/src/change_detection/differs/iterable_differs.js",
      "npm:@angular/core@2.0.0-rc.1/src/linker/exceptions.js",
      "npm:@angular/core@2.0.0-rc.1/src/linker/element.js",
      "npm:@angular/core@2.0.0-rc.1/src/linker/view_container_ref.js",
      "npm:@angular/core@2.0.0-rc.1/src/profile/profile.js",
      "npm:@angular/core@2.0.0-rc.1/src/profile/wtf_impl.js",
      "npm:@angular/core@2.0.0-rc.1/src/linker/element_ref.js",
      "npm:@angular/core@2.0.0-rc.1/src/security.js",
      "npm:@angular/core@2.0.0-rc.1/src/linker/view.js",
      "npm:@angular/core@2.0.0-rc.1/src/linker/element_injector.js",
      "npm:@angular/core@2.0.0-rc.1/src/linker/view_ref.js",
      "npm:@angular/core@2.0.0-rc.1/src/facade/async.js",
      "npm:rxjs@5.0.0-beta.7/operator/toPromise.js",
      "npm:rxjs@5.0.0-beta.7/observable/PromiseObservable.js",
      "npm:@angular/core@2.0.0-rc.1/src/facade/promise.js",
      "npm:@angular/core@2.0.0-rc.1/src/linker/component_resolver.js",
      "npm:@angular/core@2.0.0-rc.1/src/linker/component_factory.js",
      "npm:@angular/core@2.0.0-rc.1/src/metadata/lifecycle_hooks.js",
      "npm:@angular/core@2.0.0-rc.1/src/application_common_providers.js",
      "npm:@angular/core@2.0.0-rc.1/src/linker/dynamic_component_loader.js",
      "npm:@angular/core@2.0.0-rc.1/src/application_ref.js",
      "npm:@angular/core@2.0.0-rc.1/src/testability/testability.js",
      "npm:@angular/core@2.0.0-rc.1/src/zone/ng_zone.js",
      "npm:@angular/core@2.0.0-rc.1/src/zone/ng_zone_impl.js",
      "npm:@angular/core@2.0.0-rc.1/src/platform_common_providers.js",
      "npm:@angular/core@2.0.0-rc.1/src/platform_directives_and_pipes.js",
      "npm:@angular/core@2.0.0-rc.1/src/change_detection.js",
      "npm:@angular/core@2.0.0-rc.1/src/linker.js",
      "npm:@angular/core@2.0.0-rc.1/src/linker/query_list.js",
      "npm:@angular/core@2.0.0-rc.1/src/render.js",
      "npm:@angular/core@2.0.0-rc.1/src/zone.js",
      "npm:@angular/core@2.0.0-rc.1/src/util.js",
      "npm:@angular/core@2.0.0-rc.1/src/metadata.js",
      "npm:@angular/core@2.0.0-rc.1/src/metadata/directives.js",
      "npm:@angular/core@2.0.0-rc.1/src/metadata/di.js",
      "npm:@angular/http@2.0.0-rc.1/src/base_request_options.js",
      "npm:@angular/http@2.0.0-rc.1/src/backends/browser_jsonp.js",
      "npm:@angular/http@2.0.0-rc.1/src/backends/browser_xhr.js",
      "npm:@angular/http@2.0.0-rc.1/src/backends/jsonp_backend.js",
      "npm:@angular/http@2.0.0-rc.1/src/backends/xhr_backend.js",
      "npm:@angular/http@2.0.0-rc.1/src/http.js",
      "npm:ng2-translate@2.1.0/src/translate.pipe.js",
      "npm:@angular/router@2.0.0-rc.1.js",
      "npm:@angular/router@2.0.0-rc.1/index.js",
      "npm:@angular/router@2.0.0-rc.1/src/directives/router_link.js",
      "npm:@angular/router@2.0.0-rc.1/src/facade/async.js",
      "npm:@angular/router@2.0.0-rc.1/src/facade/promise.js",
      "npm:@angular/router@2.0.0-rc.1/src/facade/lang.js",
      "npm:@angular/router@2.0.0-rc.1/src/segments.js",
      "npm:@angular/router@2.0.0-rc.1/src/facade/collection.js",
      "npm:@angular/router@2.0.0-rc.1/src/router.js",
      "npm:@angular/router@2.0.0-rc.1/src/constants.js",
      "npm:@angular/router@2.0.0-rc.1/src/lifecycle_reflector.js",
      "npm:@angular/router@2.0.0-rc.1/src/link.js",
      "npm:@angular/router@2.0.0-rc.1/src/facade/exceptions.js",
      "npm:@angular/router@2.0.0-rc.1/src/facade/exception_handler.js",
      "npm:@angular/router@2.0.0-rc.1/src/facade/base_wrapped_exception.js",
      "npm:@angular/router@2.0.0-rc.1/src/recognize.js",
      "npm:@angular/router@2.0.0-rc.1/src/metadata/metadata.js",
      "npm:@angular/router@2.0.0-rc.1/src/directives/router_outlet.js",
      "npm:@angular/router@2.0.0-rc.1/src/router_providers.js",
      "npm:@angular/common@2.0.0-rc.1.js",
      "npm:@angular/common@2.0.0-rc.1/index.js",
      "npm:@angular/common@2.0.0-rc.1/src/location.js",
      "npm:@angular/common@2.0.0-rc.1/src/location/location.js",
      "npm:@angular/common@2.0.0-rc.1/src/location/location_strategy.js",
      "npm:@angular/common@2.0.0-rc.1/src/facade/async.js",
      "npm:@angular/common@2.0.0-rc.1/src/facade/promise.js",
      "npm:@angular/common@2.0.0-rc.1/src/facade/lang.js",
      "npm:@angular/common@2.0.0-rc.1/src/location/path_location_strategy.js",
      "npm:@angular/common@2.0.0-rc.1/src/location/platform_location.js",
      "npm:@angular/common@2.0.0-rc.1/src/facade/exceptions.js",
      "npm:@angular/common@2.0.0-rc.1/src/facade/exception_handler.js",
      "npm:@angular/common@2.0.0-rc.1/src/facade/collection.js",
      "npm:@angular/common@2.0.0-rc.1/src/facade/base_wrapped_exception.js",
      "npm:@angular/common@2.0.0-rc.1/src/location/hash_location_strategy.js",
      "npm:@angular/common@2.0.0-rc.1/src/common_directives.js",
      "npm:@angular/common@2.0.0-rc.1/src/directives.js",
      "npm:@angular/common@2.0.0-rc.1/src/directives/core_directives.js",
      "npm:@angular/common@2.0.0-rc.1/src/directives/ng_plural.js",
      "npm:@angular/common@2.0.0-rc.1/src/directives/ng_switch.js",
      "npm:@angular/common@2.0.0-rc.1/src/directives/ng_style.js",
      "npm:@angular/common@2.0.0-rc.1/src/directives/ng_template_outlet.js",
      "npm:@angular/common@2.0.0-rc.1/src/directives/ng_if.js",
      "npm:@angular/common@2.0.0-rc.1/src/directives/ng_for.js",
      "npm:@angular/common@2.0.0-rc.1/src/directives/ng_class.js",
      "npm:@angular/common@2.0.0-rc.1/src/directives/observable_list_diff.js",
      "npm:@angular/common@2.0.0-rc.1/src/forms.js",
      "npm:@angular/common@2.0.0-rc.1/src/forms/directives/radio_control_value_accessor.js",
      "npm:@angular/common@2.0.0-rc.1/src/forms/directives/ng_control.js",
      "npm:@angular/common@2.0.0-rc.1/src/forms/directives/abstract_control_directive.js",
      "npm:@angular/common@2.0.0-rc.1/src/forms/directives/control_value_accessor.js",
      "npm:@angular/common@2.0.0-rc.1/src/forms/form_builder.js",
      "npm:@angular/common@2.0.0-rc.1/src/forms/model.js",
      "npm:@angular/common@2.0.0-rc.1/src/forms/directives/validators.js",
      "npm:@angular/common@2.0.0-rc.1/src/forms/validators.js",
      "npm:@angular/common@2.0.0-rc.1/src/forms/directives.js",
      "npm:@angular/common@2.0.0-rc.1/src/forms/directives/select_control_value_accessor.js",
      "npm:@angular/common@2.0.0-rc.1/src/forms/directives/ng_control_status.js",
      "npm:@angular/common@2.0.0-rc.1/src/forms/directives/number_value_accessor.js",
      "npm:@angular/common@2.0.0-rc.1/src/forms/directives/checkbox_value_accessor.js",
      "npm:@angular/common@2.0.0-rc.1/src/forms/directives/default_value_accessor.js",
      "npm:@angular/common@2.0.0-rc.1/src/forms/directives/ng_form.js",
      "npm:@angular/common@2.0.0-rc.1/src/forms/directives/shared.js",
      "npm:@angular/common@2.0.0-rc.1/src/forms/directives/normalize_validator.js",
      "npm:@angular/common@2.0.0-rc.1/src/forms/directives/control_container.js",
      "npm:@angular/common@2.0.0-rc.1/src/forms/directives/ng_form_model.js",
      "npm:@angular/common@2.0.0-rc.1/src/forms/directives/ng_control_group.js",
      "npm:@angular/common@2.0.0-rc.1/src/forms/directives/ng_model.js",
      "npm:@angular/common@2.0.0-rc.1/src/forms/directives/ng_form_control.js",
      "npm:@angular/common@2.0.0-rc.1/src/forms/directives/ng_control_name.js",
      "npm:@angular/common@2.0.0-rc.1/src/pipes.js",
      "npm:@angular/common@2.0.0-rc.1/src/pipes/common_pipes.js",
      "npm:@angular/common@2.0.0-rc.1/src/pipes/i18n_select_pipe.js",
      "npm:@angular/common@2.0.0-rc.1/src/pipes/invalid_pipe_argument_exception.js",
      "npm:@angular/common@2.0.0-rc.1/src/pipes/i18n_plural_pipe.js",
      "npm:@angular/common@2.0.0-rc.1/src/pipes/replace_pipe.js",
      "npm:@angular/common@2.0.0-rc.1/src/pipes/number_pipe.js",
      "npm:@angular/common@2.0.0-rc.1/src/facade/intl.js",
      "npm:@angular/common@2.0.0-rc.1/src/pipes/date_pipe.js",
      "npm:@angular/common@2.0.0-rc.1/src/pipes/slice_pipe.js",
      "npm:@angular/common@2.0.0-rc.1/src/pipes/json_pipe.js",
      "npm:@angular/common@2.0.0-rc.1/src/pipes/lowercase_pipe.js",
      "npm:@angular/common@2.0.0-rc.1/src/pipes/uppercase_pipe.js",
      "npm:@angular/common@2.0.0-rc.1/src/pipes/async_pipe.js",
      "npm:@angular/platform-browser@2.0.0-rc.1.js",
      "npm:@angular/platform-browser@2.0.0-rc.1/index.js",
      "npm:@angular/platform-browser@2.0.0-rc.1/src/platform_browser.js",
      "npm:@angular/platform-browser@2.0.0-rc.1/src/platform_browser_static.js",
      "npm:@angular/platform-browser@2.0.0-rc.1/src/browser/location/browser_platform_location.js",
      "npm:@angular/platform-browser@2.0.0-rc.1/src/dom/dom_adapter.js",
      "npm:@angular/platform-browser@2.0.0-rc.1/src/facade/lang.js",
      "npm:@angular/platform-browser@2.0.0-rc.1/src/dom/debug/ng_probe.js",
      "npm:@angular/platform-browser@2.0.0-rc.1/src/dom/dom_renderer.js",
      "npm:@angular/platform-browser@2.0.0-rc.1/src/dom/util.js",
      "npm:@angular/platform-browser@2.0.0-rc.1/src/dom/dom_tokens.js",
      "npm:@angular/platform-browser@2.0.0-rc.1/src/dom/events/event_manager.js",
      "npm:@angular/platform-browser@2.0.0-rc.1/src/facade/collection.js",
      "npm:@angular/platform-browser@2.0.0-rc.1/src/facade/exceptions.js",
      "npm:@angular/platform-browser@2.0.0-rc.1/src/facade/exception_handler.js",
      "npm:@angular/platform-browser@2.0.0-rc.1/src/facade/base_wrapped_exception.js",
      "npm:@angular/platform-browser@2.0.0-rc.1/src/dom/shared_styles_host.js",
      "npm:@angular/platform-browser@2.0.0-rc.1/src/animate/animation_builder.js",
      "npm:@angular/platform-browser@2.0.0-rc.1/src/animate/browser_details.js",
      "npm:@angular/platform-browser@2.0.0-rc.1/src/facade/math.js",
      "npm:@angular/platform-browser@2.0.0-rc.1/src/animate/css_animation_builder.js",
      "npm:@angular/platform-browser@2.0.0-rc.1/src/animate/animation.js",
      "npm:@angular/platform-browser@2.0.0-rc.1/src/animate/css_animation_options.js",
      "npm:@angular/platform-browser@2.0.0-rc.1/core_private.js",
      "npm:@angular/platform-browser@2.0.0-rc.1/src/browser_common.js",
      "npm:@angular/platform-browser@2.0.0-rc.1/src/dom/debug/by.js",
      "npm:@angular/platform-browser@2.0.0-rc.1/src/browser/tools/tools.js",
      "npm:@angular/platform-browser@2.0.0-rc.1/src/browser/tools/common_tools.js",
      "npm:@angular/platform-browser@2.0.0-rc.1/src/facade/browser.js",
      "npm:@angular/platform-browser@2.0.0-rc.1/src/browser/title.js",
      "npm:@angular/platform-browser@2.0.0-rc.1/src/dom/events/hammer_gestures.js",
      "npm:@angular/platform-browser@2.0.0-rc.1/src/dom/events/hammer_common.js",
      "npm:@angular/platform-browser@2.0.0-rc.1/src/dom/events/dom_events.js",
      "npm:@angular/platform-browser@2.0.0-rc.1/src/dom/events/key_events.js",
      "npm:@angular/platform-browser@2.0.0-rc.1/src/browser/testability.js",
      "npm:@angular/platform-browser@2.0.0-rc.1/src/browser/browser_adapter.js",
      "npm:@angular/platform-browser@2.0.0-rc.1/src/browser/generic_browser_adapter.js",
      "npm:@angular/platform-browser@2.0.0-rc.1/src/security/dom_sanitization_service.js",
      "npm:@angular/platform-browser@2.0.0-rc.1/src/security/style_sanitizer.js",
      "npm:@angular/platform-browser@2.0.0-rc.1/src/security/url_sanitizer.js",
      "npm:@angular/platform-browser@2.0.0-rc.1/private_export.js",
      "npm:@angular/router@2.0.0-rc.1/src/router_providers_common.js",
      "npm:@angular/router@2.0.0-rc.1/src/router_url_serializer.js",
      "npm:@angular/router@2.0.0-rc.1/src/metadata/decorators.js",
      "npm:@angular/router@2.0.0-rc.1/src/core_private.js",
      "npm:@angular/platform-browser-dynamic@2.0.0-rc.1.js",
      "npm:@angular/platform-browser-dynamic@2.0.0-rc.1/index.js",
      "npm:@angular/platform-browser-dynamic@2.0.0-rc.1/platform_browser_dynamic.js",
      "npm:@angular/platform-browser-dynamic@2.0.0-rc.1/core_private.js",
      "npm:@angular/platform-browser-dynamic@2.0.0-rc.1/src/xhr/xhr_impl.js",
      "npm:@angular/platform-browser-dynamic@2.0.0-rc.1/src/facade/lang.js",
      "npm:@angular/platform-browser-dynamic@2.0.0-rc.1/src/facade/promise.js",
      "npm:@angular/compiler@2.0.0-rc.1.js",
      "npm:@angular/compiler@2.0.0-rc.1/index.js",
      "npm:@angular/compiler@2.0.0-rc.1/compiler.js",
      "npm:@angular/compiler@2.0.0-rc.1/private_export.js",
      "npm:@angular/compiler@2.0.0-rc.1/src/output/path_util.js",
      "npm:@angular/compiler@2.0.0-rc.1/src/facade/lang.js",
      "npm:@angular/compiler@2.0.0-rc.1/src/facade/exceptions.js",
      "npm:@angular/compiler@2.0.0-rc.1/src/facade/exception_handler.js",
      "npm:@angular/compiler@2.0.0-rc.1/src/facade/collection.js",
      "npm:@angular/compiler@2.0.0-rc.1/src/facade/base_wrapped_exception.js",
      "npm:@angular/compiler@2.0.0-rc.1/src/selector.js",
      "npm:@angular/compiler@2.0.0-rc.1/src/template_ast.js",
      "npm:@angular/compiler@2.0.0-rc.1/src/compiler.js",
      "npm:@angular/compiler@2.0.0-rc.1/src/expression_parser/lexer.js",
      "npm:@angular/compiler@2.0.0-rc.1/src/expression_parser/parser.js",
      "npm:@angular/compiler@2.0.0-rc.1/src/expression_parser/ast.js",
      "npm:@angular/compiler@2.0.0-rc.1/src/schema/dom_element_schema_registry.js",
      "npm:@angular/compiler@2.0.0-rc.1/src/schema/element_schema_registry.js",
      "npm:@angular/compiler@2.0.0-rc.1/core_private.js",
      "npm:@angular/compiler@2.0.0-rc.1/src/view_compiler/view_compiler.js",
      "npm:@angular/compiler@2.0.0-rc.1/src/config.js",
      "npm:@angular/compiler@2.0.0-rc.1/src/identifiers.js",
      "npm:@angular/compiler@2.0.0-rc.1/src/util.js",
      "npm:@angular/compiler@2.0.0-rc.1/src/compile_metadata.js",
      "npm:@angular/compiler@2.0.0-rc.1/src/url_resolver.js",
      "npm:@angular/compiler@2.0.0-rc.1/src/view_compiler/view_binder.js",
      "npm:@angular/compiler@2.0.0-rc.1/src/view_compiler/lifecycle_binder.js",
      "npm:@angular/compiler@2.0.0-rc.1/src/view_compiler/constants.js",
      "npm:@angular/compiler@2.0.0-rc.1/src/output/output_ast.js",
      "npm:@angular/compiler@2.0.0-rc.1/src/view_compiler/event_binder.js",
      "npm:@angular/compiler@2.0.0-rc.1/src/view_compiler/compile_binding.js",
      "npm:@angular/compiler@2.0.0-rc.1/src/view_compiler/expression_converter.js",
      "npm:@angular/compiler@2.0.0-rc.1/src/view_compiler/compile_method.js",
      "npm:@angular/compiler@2.0.0-rc.1/src/view_compiler/property_binder.js",
      "npm:@angular/compiler@2.0.0-rc.1/src/view_compiler/view_builder.js",
      "npm:@angular/compiler@2.0.0-rc.1/src/view_compiler/util.js",
      "npm:@angular/compiler@2.0.0-rc.1/src/view_compiler/compile_element.js",
      "npm:@angular/compiler@2.0.0-rc.1/src/view_compiler/compile_query.js",
      "npm:@angular/compiler@2.0.0-rc.1/src/view_compiler/compile_view.js",
      "npm:@angular/compiler@2.0.0-rc.1/src/view_compiler/compile_pipe.js",
      "npm:@angular/compiler@2.0.0-rc.1/src/style_compiler.js",
      "npm:@angular/compiler@2.0.0-rc.1/src/style_url_resolver.js",
      "npm:@angular/compiler@2.0.0-rc.1/src/shadow_css.js",
      "npm:@angular/compiler@2.0.0-rc.1/src/metadata_resolver.js",
      "npm:@angular/compiler@2.0.0-rc.1/src/assertions.js",
      "npm:@angular/compiler@2.0.0-rc.1/src/directive_lifecycle_reflector.js",
      "npm:@angular/compiler@2.0.0-rc.1/src/view_resolver.js",
      "npm:@angular/compiler@2.0.0-rc.1/src/pipe_resolver.js",
      "npm:@angular/compiler@2.0.0-rc.1/src/directive_resolver.js",
      "npm:@angular/compiler@2.0.0-rc.1/src/directive_normalizer.js",
      "npm:@angular/compiler@2.0.0-rc.1/src/template_preparser.js",
      "npm:@angular/compiler@2.0.0-rc.1/src/html_tags.js",
      "npm:@angular/compiler@2.0.0-rc.1/src/html_parser.js",
      "npm:@angular/compiler@2.0.0-rc.1/src/parse_util.js",
      "npm:@angular/compiler@2.0.0-rc.1/src/html_lexer.js",
      "npm:@angular/compiler@2.0.0-rc.1/src/html_ast.js",
      "npm:@angular/compiler@2.0.0-rc.1/src/xhr.js",
      "npm:@angular/compiler@2.0.0-rc.1/src/facade/async.js",
      "npm:@angular/compiler@2.0.0-rc.1/src/facade/promise.js",
      "npm:@angular/compiler@2.0.0-rc.1/src/runtime_compiler.js",
      "npm:@angular/compiler@2.0.0-rc.1/src/output/interpretive_view.js",
      "npm:@angular/compiler@2.0.0-rc.1/src/output/output_interpreter.js",
      "npm:@angular/compiler@2.0.0-rc.1/src/output/ts_emitter.js",
      "npm:@angular/compiler@2.0.0-rc.1/src/output/abstract_emitter.js",
      "npm:@angular/compiler@2.0.0-rc.1/src/output/dart_emitter.js",
      "npm:@angular/compiler@2.0.0-rc.1/src/output/output_jit.js",
      "npm:@angular/compiler@2.0.0-rc.1/src/output/abstract_js_emitter.js",
      "npm:@angular/compiler@2.0.0-rc.1/src/template_parser.js",
      "npm:@angular/compiler@2.0.0-rc.1/src/provider_parser.js",
      "npm:@angular/compiler@2.0.0-rc.1/src/offline_compiler.js",
      "npm:@angular/platform-browser-dynamic@2.0.0-rc.1/src/xhr/xhr_cache.js",
      "npm:@angular/platform-browser-dynamic@2.0.0-rc.1/src/facade/exceptions.js",
      "npm:@angular/platform-browser-dynamic@2.0.0-rc.1/src/facade/exception_handler.js",
      "npm:@angular/platform-browser-dynamic@2.0.0-rc.1/src/facade/collection.js",
      "npm:@angular/platform-browser-dynamic@2.0.0-rc.1/src/facade/base_wrapped_exception.js"
    ]
  },

  meta: {
    "app/*": {
      "format": "register"
    }
  },

  map: {
    "@angular/common": "npm:@angular/common@2.0.0-rc.1",
    "@angular/compiler": "npm:@angular/compiler@2.0.0-rc.1",
    "@angular/core": "npm:@angular/core@2.0.0-rc.1",
    "@angular/http": "npm:@angular/http@2.0.0-rc.1",
    "@angular/platform-browser": "npm:@angular/platform-browser@2.0.0-rc.1",
    "@angular/platform-browser-dynamic": "npm:@angular/platform-browser-dynamic@2.0.0-rc.1",
    "@angular/router": "npm:@angular/router@2.0.0-rc.1",
    "es6-shim": "github:es-shims/es6-shim@0.35.1",
    "ng2-translate": "npm:ng2-translate@2.1.0",
    "reflect-metadata": "npm:reflect-metadata@0.1.3",
    "rxjs": "npm:rxjs@5.0.0-beta.7",
    "zone.js": "npm:zone.js@0.6.12",
    "github:jspm/nodelibs-assert@0.1.0": {
      "assert": "npm:assert@1.4.0"
    },
    "github:jspm/nodelibs-buffer@0.1.0": {
      "buffer": "npm:buffer@3.6.0"
    },
    "github:jspm/nodelibs-constants@0.1.0": {
      "constants-browserify": "npm:constants-browserify@0.0.1"
    },
    "github:jspm/nodelibs-crypto@0.1.0": {
      "crypto-browserify": "npm:crypto-browserify@3.11.0"
    },
    "github:jspm/nodelibs-events@0.1.1": {
      "events": "npm:events@1.0.2"
    },
    "github:jspm/nodelibs-path@0.1.0": {
      "path-browserify": "npm:path-browserify@0.0.0"
    },
    "github:jspm/nodelibs-process@0.1.2": {
      "process": "npm:process@0.11.3"
    },
    "github:jspm/nodelibs-stream@0.1.0": {
      "stream-browserify": "npm:stream-browserify@1.0.0"
    },
    "github:jspm/nodelibs-string_decoder@0.1.0": {
      "string_decoder": "npm:string_decoder@0.10.31"
    },
    "github:jspm/nodelibs-util@0.1.0": {
      "util": "npm:util@0.10.3"
    },
    "github:jspm/nodelibs-vm@0.1.0": {
      "vm-browserify": "npm:vm-browserify@0.0.4"
    },
    "npm:@angular/common@2.0.0-rc.1": {
      "@angular/core": "npm:@angular/core@2.0.0-rc.1",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:@angular/compiler@2.0.0-rc.1": {
      "@angular/core": "npm:@angular/core@2.0.0-rc.1",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:@angular/core@2.0.0-rc.1": {
      "process": "github:jspm/nodelibs-process@0.1.2",
      "rxjs": "npm:rxjs@5.0.0-beta.6",
      "zone.js": "npm:zone.js@0.6.12"
    },
    "npm:@angular/http@2.0.0-rc.1": {
      "@angular/core": "npm:@angular/core@2.0.0-rc.1",
      "rxjs": "npm:rxjs@5.0.0-beta.7"
    },
    "npm:@angular/platform-browser-dynamic@2.0.0-rc.1": {
      "@angular/common": "npm:@angular/common@2.0.0-rc.1",
      "@angular/compiler": "npm:@angular/compiler@2.0.0-rc.1",
      "@angular/core": "npm:@angular/core@2.0.0-rc.1",
      "@angular/platform-browser": "npm:@angular/platform-browser@2.0.0-rc.1",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:@angular/platform-browser@2.0.0-rc.1": {
      "@angular/common": "npm:@angular/common@2.0.0-rc.1",
      "@angular/compiler": "npm:@angular/compiler@2.0.0-rc.1",
      "@angular/core": "npm:@angular/core@2.0.0-rc.1",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:@angular/router@2.0.0-rc.1": {
      "@angular/common": "npm:@angular/common@2.0.0-rc.1",
      "@angular/core": "npm:@angular/core@2.0.0-rc.1",
      "@angular/platform-browser": "npm:@angular/platform-browser@2.0.0-rc.1"
    },
    "npm:asn1.js@4.6.0": {
      "assert": "github:jspm/nodelibs-assert@0.1.0",
      "bn.js": "npm:bn.js@4.11.3",
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "inherits": "npm:inherits@2.0.1",
      "minimalistic-assert": "npm:minimalistic-assert@1.0.0",
      "vm": "github:jspm/nodelibs-vm@0.1.0"
    },
    "npm:assert@1.4.0": {
      "assert": "github:jspm/nodelibs-assert@0.1.0",
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "buffer-shims": "npm:buffer-shims@1.0.0",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "util": "npm:util@0.10.3"
    },
    "npm:bn.js@4.11.3": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0"
    },
    "npm:browserify-aes@1.0.6": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "buffer-xor": "npm:buffer-xor@1.0.3",
      "cipher-base": "npm:cipher-base@1.0.2",
      "create-hash": "npm:create-hash@1.1.2",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "evp_bytestokey": "npm:evp_bytestokey@1.0.0",
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "inherits": "npm:inherits@2.0.1",
      "systemjs-json": "github:systemjs/plugin-json@0.1.2"
    },
    "npm:browserify-cipher@1.0.0": {
      "browserify-aes": "npm:browserify-aes@1.0.6",
      "browserify-des": "npm:browserify-des@1.0.0",
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "evp_bytestokey": "npm:evp_bytestokey@1.0.0"
    },
    "npm:browserify-des@1.0.0": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "cipher-base": "npm:cipher-base@1.0.2",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "des.js": "npm:des.js@1.0.0",
      "inherits": "npm:inherits@2.0.1"
    },
    "npm:browserify-rsa@4.0.1": {
      "bn.js": "npm:bn.js@4.11.3",
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "constants": "github:jspm/nodelibs-constants@0.1.0",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "randombytes": "npm:randombytes@2.0.3"
    },
    "npm:browserify-sign@4.0.0": {
      "bn.js": "npm:bn.js@4.11.3",
      "browserify-rsa": "npm:browserify-rsa@4.0.1",
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "create-hash": "npm:create-hash@1.1.2",
      "create-hmac": "npm:create-hmac@1.1.4",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "elliptic": "npm:elliptic@6.2.3",
      "inherits": "npm:inherits@2.0.1",
      "parse-asn1": "npm:parse-asn1@5.0.0",
      "stream": "github:jspm/nodelibs-stream@0.1.0"
    },
    "npm:buffer-shims@1.0.0": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0"
    },
    "npm:buffer-xor@1.0.3": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "systemjs-json": "github:systemjs/plugin-json@0.1.2"
    },
    "npm:buffer@3.6.0": {
      "base64-js": "npm:base64-js@0.0.8",
      "child_process": "github:jspm/nodelibs-child_process@0.1.0",
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "ieee754": "npm:ieee754@1.1.6",
      "isarray": "npm:isarray@1.0.0",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:cipher-base@1.0.2": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "inherits": "npm:inherits@2.0.1",
      "stream": "github:jspm/nodelibs-stream@0.1.0",
      "string_decoder": "github:jspm/nodelibs-string_decoder@0.1.0"
    },
    "npm:constants-browserify@0.0.1": {
      "systemjs-json": "github:systemjs/plugin-json@0.1.2"
    },
    "npm:core-util-is@1.0.2": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0"
    },
    "npm:create-ecdh@4.0.0": {
      "bn.js": "npm:bn.js@4.11.3",
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "elliptic": "npm:elliptic@6.2.3"
    },
    "npm:create-hash@1.1.2": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "cipher-base": "npm:cipher-base@1.0.2",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "inherits": "npm:inherits@2.0.1",
      "ripemd160": "npm:ripemd160@1.0.1",
      "sha.js": "npm:sha.js@2.4.5"
    },
    "npm:create-hmac@1.1.4": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "create-hash": "npm:create-hash@1.1.2",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "inherits": "npm:inherits@2.0.1",
      "stream": "github:jspm/nodelibs-stream@0.1.0"
    },
    "npm:crypto-browserify@3.11.0": {
      "browserify-cipher": "npm:browserify-cipher@1.0.0",
      "browserify-sign": "npm:browserify-sign@4.0.0",
      "create-ecdh": "npm:create-ecdh@4.0.0",
      "create-hash": "npm:create-hash@1.1.2",
      "create-hmac": "npm:create-hmac@1.1.4",
      "diffie-hellman": "npm:diffie-hellman@5.0.2",
      "inherits": "npm:inherits@2.0.1",
      "pbkdf2": "npm:pbkdf2@3.0.4",
      "public-encrypt": "npm:public-encrypt@4.0.0",
      "randombytes": "npm:randombytes@2.0.3"
    },
    "npm:des.js@1.0.0": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "inherits": "npm:inherits@2.0.1",
      "minimalistic-assert": "npm:minimalistic-assert@1.0.0"
    },
    "npm:diffie-hellman@5.0.2": {
      "bn.js": "npm:bn.js@4.11.3",
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "miller-rabin": "npm:miller-rabin@4.0.0",
      "randombytes": "npm:randombytes@2.0.3",
      "systemjs-json": "github:systemjs/plugin-json@0.1.2"
    },
    "npm:elliptic@6.2.3": {
      "bn.js": "npm:bn.js@4.11.3",
      "brorand": "npm:brorand@1.0.5",
      "hash.js": "npm:hash.js@1.0.3",
      "inherits": "npm:inherits@2.0.1",
      "systemjs-json": "github:systemjs/plugin-json@0.1.2"
    },
    "npm:evp_bytestokey@1.0.0": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "create-hash": "npm:create-hash@1.1.2",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0"
    },
    "npm:hash.js@1.0.3": {
      "inherits": "npm:inherits@2.0.1"
    },
    "npm:inherits@2.0.1": {
      "util": "github:jspm/nodelibs-util@0.1.0"
    },
    "npm:miller-rabin@4.0.0": {
      "bn.js": "npm:bn.js@4.11.3",
      "brorand": "npm:brorand@1.0.5"
    },
    "npm:ng2-translate@2.1.0": {
      "@angular/common": "npm:@angular/common@2.0.0-rc.1",
      "@angular/compiler": "npm:@angular/compiler@2.0.0-rc.1",
      "@angular/core": "npm:@angular/core@2.0.0-rc.1",
      "@angular/http": "npm:@angular/http@2.0.0-rc.1",
      "path": "github:jspm/nodelibs-path@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "systemjs-json": "github:systemjs/plugin-json@0.1.2"
    },
    "npm:parse-asn1@5.0.0": {
      "asn1.js": "npm:asn1.js@4.6.0",
      "browserify-aes": "npm:browserify-aes@1.0.6",
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "create-hash": "npm:create-hash@1.1.2",
      "evp_bytestokey": "npm:evp_bytestokey@1.0.0",
      "pbkdf2": "npm:pbkdf2@3.0.4",
      "systemjs-json": "github:systemjs/plugin-json@0.1.2"
    },
    "npm:path-browserify@0.0.0": {
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:pbkdf2@3.0.4": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "child_process": "github:jspm/nodelibs-child_process@0.1.0",
      "create-hmac": "npm:create-hmac@1.1.4",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "path": "github:jspm/nodelibs-path@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "systemjs-json": "github:systemjs/plugin-json@0.1.2"
    },
    "npm:process@0.11.3": {
      "assert": "github:jspm/nodelibs-assert@0.1.0"
    },
    "npm:public-encrypt@4.0.0": {
      "bn.js": "npm:bn.js@4.11.3",
      "browserify-rsa": "npm:browserify-rsa@4.0.1",
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "create-hash": "npm:create-hash@1.1.2",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "parse-asn1": "npm:parse-asn1@5.0.0",
      "randombytes": "npm:randombytes@2.0.3"
    },
    "npm:randombytes@2.0.3": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:readable-stream@1.1.14": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "core-util-is": "npm:core-util-is@1.0.2",
      "events": "github:jspm/nodelibs-events@0.1.1",
      "inherits": "npm:inherits@2.0.1",
      "isarray": "npm:isarray@0.0.1",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "stream-browserify": "npm:stream-browserify@1.0.0",
      "string_decoder": "npm:string_decoder@0.10.31"
    },
    "npm:reflect-metadata@0.1.3": {
      "assert": "github:jspm/nodelibs-assert@0.1.0",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:ripemd160@1.0.1": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:rxjs@5.0.0-beta.6": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:rxjs@5.0.0-beta.7": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "symbol-observable": "npm:symbol-observable@0.2.4"
    },
    "npm:sha.js@2.4.5": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "inherits": "npm:inherits@2.0.1",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:stream-browserify@1.0.0": {
      "events": "github:jspm/nodelibs-events@0.1.1",
      "inherits": "npm:inherits@2.0.1",
      "readable-stream": "npm:readable-stream@1.1.14"
    },
    "npm:string_decoder@0.10.31": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0"
    },
    "npm:util@0.10.3": {
      "inherits": "npm:inherits@2.0.1",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:vm-browserify@0.0.4": {
      "indexof": "npm:indexof@0.0.1"
    },
    "npm:zone.js@0.6.12": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2"
    }
  }
});
