// Angular 2
import '@angular/platform-browser';
import '@angular/platform-browser-dynamic';
import '@angular/core';
import '@angular/common';
import '@angular/router';
import '@ngx-translate/core';
// Translate
import '@ngx-translate/core';
import '@ngx-translate/http-loader';
// NGX-Bootstrap
import 'ngx-bootstrap/tabs';
import 'ngx-bootstrap/tooltip';
import 'ngx-bootstrap/rating';
import 'ngx-bootstrap/dropdown';
import 'ngx-bootstrap/datepicker';
import 'ngx-bootstrap/alert';
// RxJS
import 'rxjs/add/operator/map';
import 'rxjs/add/observable/throw';
import 'rxjs/add/observable/forkJoin';
import 'rxjs/add/operator/filter';
// Styles
import './assets/styles/theme.scss';
import './assets/styles/themeicons.scss';
import './assets/styles/components/breadcrumbs.scss';
import 'ngx-bootstrap/datepicker/bs-datepicker.css';
